version: '3.9'
services:
  mysql:
    image: mysql:8.0
    container_name: tienda_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: tienda_ropa
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql

volumes:
  mysql_data:
